jupyter-kernel-gateway-incorporation/jupyter-kernel-gateway-incorporation.md

This PR proposes graduating the kernel_gateway project from jupyter-incubator. I ran this by @rgbkrk who is the advisor/mentor/sponsor on the incubator proposal before opening. I'd like to open it up for comments.
I'll post this to the jupyter google group soon.
cc'ing folks who commented on the [original incubator proposal](https://github.com/jupyter-incubator/proposals/pull/3): @jasongrout @minrk @ellisonbg @sccolbert @blink1073 @freeman-lab @damianavila @Carreau @fperez @ahmadia @lbustelo @vinomaster

jupyter-incubator/kernel_gateway incorporation proposal

---

jupyter-dashboards-extension-incorporation/jupyter-dashboards-extension-incorporation.md

This PR proposes graduating the [dashboard layout extension](https://github.com/jupyter-incubator/dashboards) from jupyter-incubator. Per the roadmap and discussion at the Spring '16 dev meeting, it does **not** include the other, related projects such as the dashboards server. (We'll follow-on with a proposal for that and others.)
cc'ing folks who commented on the [original incubation proposal](https://github.com/jupyter-incubator/proposals/pull/4) to start: @vinomaster @rgbkrk @ellisonbg @fperez @Carreau @lbustelo @lmeyerov @minrk @damianavila

jupyter-incubator/dashboards incorporation proposal

---

jupyter-declarativewidgets-incorporation/jupyter-declarativewidgets-extension-incorporation.md

This PR proposes graduation of the [declarativewidgets extension](https://github.com/jupyter-incubator/declarativewidgets) from jupyter-incubator.
cc'ing folks who either commented on the [original incubation proposal](https://github.com/jupyter-incubator/proposals/pull/4) or are working in related areas: @vinomaster @rgbkrk @ellisonbg @fperez @Carreau @parente @lmeyerov @minrk @damianavila @SylvainCorlay @jdfreder @jasongrout

jupyter-incubator/declarativewidgets incorporation proposal

---

jupyter-dashboards-deployment-attic/jupyter-dashboards-deployment-attic.md

This PR proposes moving the dashboard projects remaining in jupyter-incubator to jupyter-attic, states the reasons why, summarizes what we learned from the projects, and notes some possibilities for next steps.
Comments and suggested edits are welcome from all parties.
The [new subprojects](https://github.com/jupyter/governance/blob/master/newsubprojects.md) governance doc says "a recommendation will be made by the consensus of the Steering Council (SC)". I'm taking that to mean we need at least a majority or two-thirds vote here, and so I'm adding all members of the SC as reviewers.

Proposal to move dashboard deployment repos to attic

---

jupyter-server/jupyter-server.md

After chatting with @SylvainCorlay, I'm sharing a new draft of the Jupyter Server enhancement proposal. This supersedes #21. 
Check it out! Any feedback is welcome.
You can easily view a rich display version of the proposal [here](https://github.com/jupyter/enhancement-proposals/pull/28/files?short_path=389bcd1#diff-389bcd1b95a4cf4726133a8728985375).
For those interested, I've been experimenting with some of the ideas in this proposal. Check out these repos (warning: all are **experimental**!):
* [Zsailer/notebook_server_extension](https://github.com/Zsailer/notebook_server_extension): The classic Jupyter Notebook as a server extension.
* [Zsailer/jupyter_server_extension](https://github.com/Zsailer/jupyter_server_extension): The easy way to write Jupyter server extensions that launch as …

Jupyter-server

---

README.md

I think it might be nice to number JEPs for easy reference. I needed to create a master list of JEPs that have been submitted. I added this list to the front README. They are ordered (and numbered) by their initial submission date. I also *tried* to infer their status.

Add list of JEPs (and status) to README

---

README.md

This is a follow-up PR to @Zsailer's #30.
- Assigns unique JEP ids to existing JEPs based on the original PR number
- Moves bullet list to a table
- Bolds submitted status for easy scanning of what is actively under discussion.

add table for JEPs to README

---

29-jep-process/README.md

I'm updating the header really quickly. I thought that "Submitted" was our term for a JEP in draft but I just looked at the jupyter-server JEP and the term is draft so updating it here.

Fix JEP state in header

---

29-jep-process/README.md

Some of these might already be corrected in #38.

Minor corrections to spelling, grammar

---

29-jep-process/README.md
README.md

Hey all - this PR builds off of #29 to add some language to the JEP enhancement proposal. There's a relevant issue to discuss this here: #27 
This PR is primarily about adding a "distribution" section to the "meta JEP". It mentions using a public website as an "archive" of finished JEPs. I tried not to tie it in to any specific technology, since I feel like that is more of an implementation detail and we can cross that bridge when we come to it. Hope that's OK.
The PR also:
* Cleans up a few formatting things I found in there, and adds links to the ipython/python *EP process
* Adds this JEP to the list of active JEPs in the readme (I am a bit unclear that status this JEP has...so I just left what was in the metadata for this one)
Lemme know what folks think!

Adding a distribution section to the JEP JEP and small tweaks

---

voila-incorporation/voila-incorporation.md

We propose to make Voilà an official Jupyter subproject.

Voila incorporation

---

README.md

I realized we forgot to have you add JEP #42 to the front page README.
@SylvainCorlay

add JEP 42 (voila incorporation) to readme

---

xeus-incorporation/xeus-incorporation.md

We propose to make Xeus an official Jupyter subproject.
Votes for approval:

Xeus incorporation

---

.github/pull_request_template.md
README.md
jupyter-enhancement-proposal-guidelines/JEP-TEMPLATE.md
jupyter-enhancement-proposal-guidelines/jupyter-enhancement-proposal-guidelines.md

This is one step towards implementing the meta-JEP from https://github.com/jupyter/enhancement-proposals/pull/29
It does the following:
* Updates the [enhancement proposal guidelines](https://github.com/jupyter/enhancement-proposals/blob/master/jupyter-enhancement-proposal-guidelines/jupyter-enhancement-proposal-guidelines.md) with text that was taken from the PR
- I made minor modifications for structure and cohesion, but none that should have changed the intent or meaning of the meta-JEP.
* Adds a new JEP proposal template. This is heavily-inspired by the [Rust RFC template](https://github.com/rust-lang/rfcs/blob/master/0000-template.md)
* Adds a PR template to remind people to follow the JEP process.
Happy to take comments or suggestions!

updating with new JEP process

---

.circleci/config.yml
.github/workflows/docs.yml
.gitignore
28-jupyter-server/jupyter-server.md
29-jep-process/jep-process.md
42-voila-incorporation/voila-incorporation.md
44-xeus-incorporation/xeus-incorporation.md
README.md
_config.yml
_toc.yml
jupyter-dashboards-deployment-attic/jupyter-dashboards-deployment-attic.md
jupyter-dashboards-extension-incorporation/jupyter-dashboards-extension-incorporation.md
jupyter-declarativewidgets-incorporation/jupyter-declarativewidgets-extension-incorporation.md
jupyter-enhancement-proposal-guidelines/jupyter-enhancement-proposal-guidelines.md
jupyter-enterprise-gateway-incorporation/jupyter-enterprise-gateway-incorporation.md
jupyter-kernel-gateway-incorporation/jupyter-kernel-gateway-incorporation.md

This is another implementation PR of #29 - it makes minimal changes needed to get a Jupyter Book building a website from the JEPs that are here. It also does some minor re-configuration of metadata, titles, etc to make it easier to organize and parse.
It also adds a github action that will automatically build the book and push to github-pages, and the docs will be publicly available at https://jupyter.org/enhancement-proposals
Note: there are probably other things to improve here, but I wanted to take the minimal number of steps and we can always iterate in the future if people like it
Here's how it looks:
https://2-41511140-gh.circle-artifacts.com/0/html/README.html

Minimal steps to add a website

---

jupyter-xpub/jupyter-xpub.md

A Jupyter kernel uses a PUB socket as a broadcast channel where it publishes various messages (incoming requests, outputs, events). Any client that wants to be notified of what happens in the kernel can simply subscribe to this channel via a SUB socket. The issue with this simple PUB - SUB pattern is that **there is no simple mechanism for clients to wait for their iopub subscription to be established.**
This is particularly problematic when a client needs to send a bunch of execution requests just after starting a kernel (a typical use case is the "Restart Kernel and execute all" command of Jupyter Lab, or opening a Notebook with Voilà). In that case, the client needs to ensure that its SUB socket is connected to the PUB socket of the kernel before sending any execution request, …

Replace pub with xpub proposal

---

jupyter-subdomain-for-schemas/proposal.md

Follow up to https://github.com/jupyter/enhancement-proposals/issues/107
Adds a JEP proposing  to create a subdomain under jupyter.org and a repository for publishing machine- and human-readable JSON Schemas provided by the core Jupyter ecosystem.
cc @bollwyvl @tonyfast 
- @echarles 
- @fcollonval 
- @ibdafna 
- @isabela-pf 
- @ivanov
- @minrk
- @rpwagner 
- @willingc
- @Zsailer

[JEP] subdomain and repository for publishing schemas under jupyter.org

---

108-jupyter-subdomain-for-schemas/jupyter-subdomain-for-schemas.md
README.md
_toc.yml
conf.py
requirements.txt

This just move the recently merged PR, #108, to the proper place in the sphinx docs. 
I've also added mermaid as a dependency to docs, since we used it for a flowchart.

Move the recent subdomain PR to the proper place 

---

jupyter-optional-features/jupyter-optional-features.md

Following [this discussion](https://github.com/jupyter/enhancement-proposals/pull/91#discussion_r1066735208), here is the JEP for introducing optional features in the protocol.
- @echarles 
- @fcollonval 
- @ibdafna 
- @isabela-pf 
- @ivanov
- @minrk
- @rpwagner 
- @willingc
- @Zsailer

JEP for Optional Features

---

jupyter-handshaking/jupyter-handshaking.md

The current implementation of Jupyter client makes it responsible for finding available ports and pass them to a new starting kernel. The issue is that a new process can start using one of these ports before the kernel has started, resulting in a ZMQError when the kernel starts. This is even more problematic when spawning a lot of kernels in a short laps of time, because the client may find available ports that have already been assigned to another kernel.
A workaround has been implemented for the latter case, but it does not solve the former one.
This proposal aims to fix this issue for good, with a handshaking pattern.
- @echarles 
- @fcollonval 
- @ibdafna 
- @isabela-pf 
- @ivanov
- @minrk
- @rpwagner 
- @willingc
- @Zsailer

Kernel handshaking pattern proposal

---

97-add-schema/add-schema-to-notebook-format.md

This JEP proposes to add a new top-level field, `$schema` to the notebook JSON, as such updating the notebook JSON schema. This new field deprecates `nbformat` and `nbformat_minor`.
I skipped the step of creating a GitHub issue and deciding it's a JEP in this repository after discussing with @fcollonval. There was broad consensus about this change and the fact that it's a JEP during the notebook format workshop held in Paris (Feb 28 - Mar 2), and thought it okay to file a PR straight away. I will be the shepherd.
- @echarles 
- @fcollonval 
- @ibdafna 
- @isabela-pf 
- @ivanov
- @minrk
- @rpwagner 
- @willingc
- @Zsailer

Add JEP for adding $schema to notebook format

---

118-restart-clarification/restart-clarification.md

Clarify restart to mean restart in-place

---

debugger-info-copy-to-globals/debugger-info-copy-to-globals.md

Introducing a new field to the kernel debugger_info response. 
This new field will inform the UI that the debugger supports the `copyToGlobals` request.
Related to https://github.com/jupyterlab/jupyterlab/pull/13476#discussion_r1111061085, which introduces a new feature in the debugger. It would be useful to know if this feature is supported by the kernel from UI side.
cc. @JohanMabille @krassowski 
- @echarles 
- @fcollonval 
- @gabalafou
- @ibdafna 
- @ivanov
- @marthacryan
- @minrk
- @rpwagner 
- @Zsailer

JEP for copy-to-globals support in debugger_info

---

80-kernel-info/kernel-info.md

In this JEP we propose the `kernel_info` request can be sent on both the shell and the control channels, to fix issues like [this](https://github.com/jupyter-server/jupyter_server/issues/622) and [this](https://github.com/jupyterlab/jupyterlab/issues/10174).
cc @SylvainCorlay and @minrk who I have talked to about this JEP.
- @echarles 
- @fcollonval 
- @gabalafou
- @ibdafna 
- @ivanov
- @marthacryan
- @minrk
- @rpwagner 
- @Zsailer

Support kernel_info request on the control channel

---

connectionfile-spec/connectionfile-spec.md
connectionfile-spec/connectionfile.schema.json

This proposes to specify the connection file through a JSON schema, and have the specification and documentation live in a [dedicated repo](https://github.com/jupyter-standards/kernel-protocol).
The JSON schema is joined as a standalone file.
---
I(s been a while since we proposed to move to the voting phase, let's fix it now ;) Ntice that further JSON specs should not been JEPs, but PRs to https://github.com/jupyter/schema
- @gabalafou
- @ivanov
- @jtpio 
- @marthacryan
- @martinRenou
- @minrk
- @rpwagner 
- @vidartf

JEP for specifying the connectionfile

---

kernelspec-spec/kernelspec-spec.md
kernelspec-spec/kernelspec.schema.json

This proposes to specify the kernelspec through a JSON schema, and have the specification and documentation live in a [dedicated repo](https://github.com/jupyter-standards/kernel-protocol).
The JSON schema is joined as a standalone file.
Like #106 , let's move to the voting phase. As said in [this comment](https://github.com/jupyter/enhancement-proposals/pull/105#issuecomment-1965239417), future schema should not be JEPs, but PR open to the [Jupyter Schema repo](https://github.com/jupyter/schema)
- @gabalafou
- @ivanov
- @jtpio 
- @marthacryan
- @martinRenou
- @minrk
- @rpwagner 
- @vidartf

Kernelspec JSON schema

---

kernel-subshells/kernel-subshells.md

This PR introduces kernel sub-shells to allow for concurrent code execution.
It is a JEP because it changes the kernel messaging protocol - these changes consist of (optional) additions.
- @gabalafou
- @ivanov
- @jtpio 
- @marthacryan
- @martinRenou
- @minrk
- @rpwagner 
- @vidartf

Add JEP for sub-shells
